# Copyright 2024 European Commission
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

server:
  port: 8082

spring:

  # Specify the values of the datasource
  # datasource:
  #   url: jdbc:mysql://assinadb.mysql.database.azure.com:3306/mydb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   username: franciscobraga@assinadb
  #   password: Assinadb2021

  datasource:
    url: jdbc:mysql://localhost:3306/assina?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: assinaadmin
    password: assinaadmin

  # datasource:
  #   url: jdbc:mysql://192.168.56.101:3306/assina?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   username: assinaadmin
  #   password: assinaadmin



  jpa:
    show-sql: true
    hibernate:
      # TODO replace this with ddl files
      ddl-auto: update
      naming: 
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 936504596876-6rlbd2q0le55f12g55qd7u1hlvcmn08k.apps.googleusercontent.com
            clientSecret: 4McvTO5ujBuIj2p7R-yMXVFL
            #clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
            #clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 1234121189305185277 # TODO get facebook or remove
            clientSecret: 42ffe5aa7379e8326387e0fe16f34132
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: 2e5857e1624a7f5b787c
            clientSecret: 186c64955efe28273e2d541ebe138945e5a7185a
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider: # TODO get facebook ore remove
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

# Main configurable application properties.
# Override these with matching env vars like ASSINA_AUTH_PASSPHRASE
assina:
  auth: # todo generate a token secret to share with the client side
    type: userAuthentication
    tokenSecret: 217A25432A462D4A614E645267556B58
    lifetimeMinutes: 600

  oauth2:
    # Redirect to webapp with our own JWT token after authenticating with oauth2 provider
    # these must be set up in google, github etc
    authorizedRedirectUris:
      - http://:3000/oauth2/redirect
      - http://assina.westeurope.cloudapp.azure.com/ouath2/redirect
      - http://assina.eu/ouath2/redirect

demo:
  users:
    - name: Ana Banana
      username: ana
      plainPassword: ana
      plainPIN: 1234
      email: ana@example.com
      role: ROLE_ADMIN
      numCredentials: 1
    - name: Carlos Santana
      username: carlos
      plainPassword: carlos
      plainPIN: 1234
      role: ROLE_USER
      email: carlos@example.com
      numCredentials: 3

verifier:
  url: https://verifier-backend.eudiw.dev/ui/presentations
  address: verifier-backend.eudiw.dev

csc:
  # crypto properties are used for key and cert generation and encryption
  crypto:
    # we issue our own certs for now
    issuer: assina.eu
    keyAlgorithm: RSA
    keySize: 2048
    monthsValidity: 12
    # Signature algorithm must work with the key algo above
    signatureAlgorithm: SHA256WithRSA
    # Passphrase used for encrypting private key at rest in the database
    # WARNING: This should be overridden with the (more secure) env var: CSC_CRYPTO_PASSPHRASE
    passphrase: 442A472D4B6150645367566B59703373

  # configuration for the JWT provider for SAD tokens
  sad:
    type: SAD
    lifetimeMinutes: 5
    # WARNING: This should be generated at install time
    tokenSecret: 2B4B6250655368566D59713374367639

  api:
    pageSize: 20 # if a client does not specify maxResults this is the default page size
    maxPageSize: 100 # even if a client does specify maxResults we limit it to this to avoid DOS
  info:
    # content used by the CSC info API per 11.1 in the CSC spec
    specs: "1.0.4.0"
    name: Assina
    # TODO create a log, serve it statically and move this into the InfoService
    logo: "https://service.domain.org/images/logo.png"
    # Server is established in portugal, but language is en-US only
    region: "PT"
    lang: "en-US"
    description: "A remote signature service by Assina for LEI 2021 at UMinho"
    authType:
      - oauth2code
    # google oauth
    oauth2: "google oauth"
    methods:
      - credentials/list
      - credentials/info
      - credentials/authorize
      - credentials/sendOTP
      - signatures/signHash
logging:
  level:
    org:
      springframework:
        security: INFO
