ejbca:
    # Values required to access the EJBCA:
    cahost:
    clientP12ArchiveFilepath:
    clientP12ArchivePassword:
    managementCA:

    # Endpoint:
    endpoint: /certificate/pkcs10enroll
    # Values required by the endpoint "/pkcs10enroll":
    certificateProfileName: ENDUSER
    endEntityProfileName: EMPTY
    username:
    password:
    includeChain: true

    countries:
        - country: CZ
          certificateAuthorityName: PID Issuer CA - CZ 01
        - country: EE
          certificateAuthorityName: PID Issuer CA - EE 01
        - country: EU
          certificateAuthorityName: PID Issuer CA - EU 01
        - country: LU
          certificateAuthorityName: PID Issuer CA - LU 01
        - country: NL
          certificateAuthorityName: PID Issuer CA - NL 01
        - country: PT
          certificateAuthorityName: PID Issuer CA - PT 01
        - country: default
          certificateAuthorityName: PID Issuer CA - UT 01
